annual_salary = float(input("Annual salary (£): "))
bonus_percentage = float(input("Bonus percentage: "))
pension_contribution = float(input("Pension Contribution percentage: "))
bonus_amount = annual_salary*(bonus_percentage/100)
pension = annual_salary*(pension_contribution/100)
total_contribution = annual_salary+bonus_amount+pension
print("=== Data Science Salary Calculator ===\n")
print(f"Annual salary: {annual_salary}")
print(f"Bonus %: {bonus_percentage}")
print(f"Pension %: {pension_contribution}\n")
print("--- Compensation Breakdown ---")
print(f"Base Salary: £{annual_salary:,.2f}")
print(f"Bonus ({bonus_percentage}%): £{bonus_amount:,.2f}")
print(f"Employer Pension ({pension_contribution}%): £{pension:,.2f}")
print(f"Total Compensation: £{total_contribution:,.2f}")